package com.xworkz.IPL;

import com.xworkz.IPL.dao.IpldetailsDAO;
import com.xworkz.IPL.dto.CaptainDTO;
import com.xworkz.IPL.dto.IpldetailsDTO;


public class TestIpl {
public static void main(String[] args) {
	IpldetailsDTO ipldetailsDTO=new IpldetailsDTO();
	IpldetailsDTO ipldetailsDTO1=new IpldetailsDTO();
	
	ipldetailsDTO.setTeamName("Royal challengers bangalore");
	ipldetailsDTO.setNoOfPlayers((byte)16);
	ipldetailsDTO.setViseCaptain("ABDeviliers");
	ipldetailsDTO.setOwner("United Spirits");
	
	
	ipldetailsDTO1.setTeamName("Mumbai_indians");
	ipldetailsDTO1.setNoOfPlayers((byte)11);
	ipldetailsDTO1.setViseCaptain("Sharma");
	ipldetailsDTO1.setOwner("Ambani");
	
	CaptainDTO dto=new CaptainDTO();
	dto.setCaptainName("VIRAT KOHLI");
	dto.setAucPriceinCr((byte)17);
	dto.setExperience("14 yrs of experience");
	
	CaptainDTO dto1=new CaptainDTO();
	dto1.setCaptainName("Rohith Sharma");
	dto1.setAucPriceinCr((byte)20);
	dto1.setExperience("20 yrs of experience");
	
	ipldetailsDTO.setCaptain(dto);
	ipldetailsDTO1.setCaptain(dto1);
	
	
	
	System.out.println(ipldetailsDTO.getTeamName());
	System.out.println(dto1.getAucPriceinCr());
	System.out.println();
	
	IpldetailsDAO dao = new IpldetailsDAO();
	dao.add(ipldetailsDTO);
	dao.add(ipldetailsDTO1);
	dao.printAll();
	
	 System.out.println("teamname updated by owner");
	 IpldetailsDTO ipldetailsdto=dao.updateteamNamebyOwner("United Spirits", "RCB");
     System.out.println(ipldetailsdto.toString());
     dao.printAll();
     
     

	 System.out.println("noOfplayers updated by visecaptain");
	 System.out.println();
	 IpldetailsDTO ipldetailsdto1=dao.updatenoOfPlayersbyViseCaptain((byte)12,"Sharma");
     System.out.println(ipldetailsdto1.toString());
     dao.printAll();
     
     System.out.println("data generated by teamName");
     IpldetailsDTO res=dao.getbyteamName("RCB");
     System.out.println(res);
     
    System.out.println("data generated by experience");
	IpldetailsDTO res1=dao.getbyExperience("20 yrs of experience");
	System.out.println(res1);
	
	
	   System.out.println("data deleted by owner");
		IpldetailsDTO resp1=dao.deletebyowner("AMBANI");
		System.out.println(resp1);
		dao.printAll();
	
}
}
