package com.xworkz.Movies;


import com.xworkz.Movies.dao.MoviesDAO;
import com.xworkz.Movies.dto.FilmDTO;
import com.xworkz.Movies.dto.MoviesDTO;


public class TestMovies {
	public static void main(String[] args) {
		MoviesDTO moviesDTO=new MoviesDTO();
		moviesDTO.setJoner("comedy");
		moviesDTO.setLanguage("kannada");
		moviesDTO.setDuration(2.3f);
		
		MoviesDTO moviesDTO1=new MoviesDTO();
		moviesDTO1.setJoner("horrer");
		moviesDTO1.setLanguage("malyalam");
		moviesDTO1.setDuration(2.4f);
		
		FilmDTO dto=new FilmDTO();
		dto.setMovieName("Sakkath");
		dto.setHero("GOLDEN STAR GANESH");
		dto.setHeroine("Nishvika Naidu");
		dto.setDirector("Simple suni");
		dto.setBudget(40000000);
		moviesDTO.setFilm(dto);
		
		FilmDTO dto1=new FilmDTO();
		dto1.setMovieName("COLD CASE");
		dto1.setHeroine("Sharmila Mandre");
		dto1.setHero("CHANLEE");
		dto1.setDirector("CHANTALAI");
		dto1.setBudget(60000000);
		moviesDTO1.setFilm(dto1);
		
		System.out.println(moviesDTO.getLanguage());
		System.out.println(dto.getMovieName());
		
		MoviesDAO dao=new MoviesDAO();
		dao.add(moviesDTO);
		dao.add(moviesDTO1);
		
		dao.printAll();
		System.out.println();
		
		System.out.println("language updated by joner");
		MoviesDTO  MoviesDTO1=dao.updateLanguagebyJoner("kannada english", "comedy");
	    System.out.println(MoviesDTO1.toString());
	    
	    System.out.println("duration updated by joner");
		MoviesDTO  MoviesDTO2=dao.updateDurationbyJoner(3.0f, "horrer");
	    System.out.println(MoviesDTO2.toString());
	    
	    System.out.println("data generated by language");
		MoviesDTO res=dao.getbyLanguage("malyalam");
		System.out.println(res);
		
		System.out.println("data generated by MovieName");
		MoviesDTO res1=dao.getbyMovieName("Sakkath");
		System.out.println(res1);
		  
        System.out.println("data deleted by language");
	    MoviesDTO resp=dao.deletebylanguage("malyalam");
		System.out.println(resp);
		dao.printAll();
		
		System.out.println("data deleted by joner");
		MoviesDTO resp1=dao.deletebyJoner("comedy");
		System.out.println(resp1);
		dao.printAll();		
		
	}

}
