package com.xworkz.PostOffice;



import com.xworkz.PostOffice.dao.PostOfficeDAO;
import com.xworkz.PostOffice.dto.BranchDTO;
import com.xworkz.PostOffice.dto.PostOfficeDTO;

public class TestPostOffice {
	public static void main(String[] args) {
		PostOfficeDTO postOfficeDTO=new PostOfficeDTO();
		PostOfficeDTO postOfficeDTO1=new PostOfficeDTO();
		
		postOfficeDTO.setPostMaster("ADITHYA");
		postOfficeDTO.setNoOfEmployees((byte)32);
		postOfficeDTO.setManager("AMMU");
		postOfficeDTO.setAddress("Rajajinagar");
		
		postOfficeDTO1.setPostMaster("AMAR");
		postOfficeDTO1.setNoOfEmployees((byte)32);
		postOfficeDTO1.setManager("AMRUTHA");
		postOfficeDTO1.setAddress("leggere");
		
		BranchDTO dto=new BranchDTO();
		BranchDTO dto1=new BranchDTO();
		
		dto.setBranchCode("KARP0061");
		dto.setState("karnataka");
		dto.setAddress("Rajajinagar");
		
		
		dto1.setBranchCode("AP0071");
		dto1.setState("Andrapradesh");
		dto1.setAddress("Rajaji");
		postOfficeDTO.setBranch(dto);
		postOfficeDTO1.setBranch(dto1);
		
	   System.out.println(postOfficeDTO.getPostMaster());
	   System.out.println(dto.getBranchCode());
	   System.out.println();
	   
	   PostOfficeDAO dao = new PostOfficeDAO();
	   dao.add(postOfficeDTO);
	   dao.add(postOfficeDTO1);
	   dao.printAll();
	   
	    System.out.println("employees updated by manager");
		PostOfficeDTO  postOfficeDTO2=dao.updatenoOfEmployeesbyManager((byte)34, "AMMU");
	    System.out.println(postOfficeDTO2.toString());
	    
	    System.out.println("address updated by PostMaster");
		PostOfficeDTO  postOfficeDTO3=dao.updateaddressbyPostMaster("PEENYA", "AMAR");
	    System.out.println(postOfficeDTO3.toString());
	    
	    
	    System.out.println("data generated by Manager");
	     PostOfficeDTO res=dao.getbyManager("AMRUTHA");
	     System.out.println(res);
	     
	     System.out.println("data generated by BranchCode");
	     PostOfficeDTO res1=dao.getbyBranchCode("KARP0061");
	     System.out.println(res1);
	     
	     
	     
	     
	       System.out.println();
	       System.out.println("data deleted by address");
		   PostOfficeDTO ews =dao.deletebyaddress("leggere");
		   System.out.println(ews);
		  
		   System.out.println();
		   System.out.println("data deleted by postmaster");
		   PostOfficeDTO delete =dao.deletebyPostMaster("ADITHYA");
		   System.out.println(delete);
		   dao.printAll();
		  
	     
	   }

}
