package com.xworkz.Radio;

import com.xworkz.Radio.dao.RadiodetailsDAO;
import com.xworkz.Radio.dto.RadiodetailsDTO;
import com.xworkz.Radio.dto.SizeDTO;

public class TestRadio {
	public static void main(String[] args) {
	RadiodetailsDTO radiodetailsDTO=new RadiodetailsDTO();
	RadiodetailsDTO radiodetailsDTO1=new RadiodetailsDTO();
	RadiodetailsDTO radiodetailsDTO2=new RadiodetailsDTO();
	
	radiodetailsDTO1.setCompany("akashvani");
	radiodetailsDTO1.setColor("black");
	radiodetailsDTO1.setPrice(1000);
	radiodetailsDTO1.setNoOfRS((byte)15);
	
	
	radiodetailsDTO.setCompany("Ajanta");
	radiodetailsDTO.setPrice(899);
	radiodetailsDTO.setColor("gray");
	radiodetailsDTO.setNoOfRS((byte)10);
	
	
	radiodetailsDTO2.setCompany("philips");
	radiodetailsDTO2.setColor("white");
	radiodetailsDTO2.setPrice(700);
	radiodetailsDTO2.setNoOfRS((byte)20);
	
	
	
	SizeDTO dto=new SizeDTO();
	dto.setHeight(5.3f);
	dto.setLength(10.2f);
	dto.setWidth(4);
	
	SizeDTO dto1=new SizeDTO();
	dto1.setHeight(5.3f);
	dto1.setLength(10.2f);
	dto1.setWidth(6);
	
	SizeDTO dto2=new SizeDTO();
	dto2.setHeight(3.2f);
	dto2.setLength(7.3f);
	dto2.setWidth(5);
	
	
	
	radiodetailsDTO.setSize(dto);
	radiodetailsDTO1.setSize(dto1);
	radiodetailsDTO2.setSize(dto2);
	
	
	System.out.println(radiodetailsDTO.getColor());
	System.out.println();
	
	RadiodetailsDAO dao = new RadiodetailsDAO();
	dao.add(radiodetailsDTO);
	dao.add(radiodetailsDTO1);
	dao.add(radiodetailsDTO2);
    dao.printAll();  
    
   System.out.println("price updated by color");
	 RadiodetailsDTO radiodetailsdto=dao.updatePricebyColor(1000, "gray");
     System.out.println(radiodetailsdto.toString());
     
     System.out.println("price updated by noOfRS");
     RadiodetailsDTO radiodetailsdto1=dao.updatePricebynoOfRS(1500, (byte)20);
     System.out.println(radiodetailsdto1);
     
     System.out.println("company updated by color");
     RadiodetailsDTO radiodetailsdto2=dao.updateCompanybycolor("Ajantha ", "gray");
     System.out.println(radiodetailsdto2);
     
	 System.out.println("data generated by width");
     RadiodetailsDTO details2=dao.getbyWidth(4);
     System.out.println(details2);
     
     System.out.println("data generated by price");
     RadiodetailsDTO details3=dao.getbyPrice(1500);
     System.out.println(details3);
     
     System.out.println("data generated by color");
     RadiodetailsDTO details4=dao.getbyColor("gray");
     System.out.println(details4);
     
     
     
	 System.out.println("data deleted by color");  
     RadiodetailsDTO del=dao.deletebyColor("white");
     dao.printAll();
		System.out.println(del);	
		 System.out.println(radiodetailsDTO1.toString());
     
     System.out.println("data deleted");  
     RadiodetailsDTO isdelete=dao.deletebyCompany("Ajanta");
		System.out.println(isdelete);	
		 dao.printAll();
		 System.out.println(radiodetailsDTO1.toString());
		 
		 System.out.println("data deleted by sizedto");  
	     RadiodetailsDTO delete=dao.deletebyHeight(5.3f);
			System.out.println(delete);	
			 dao.printAll();
			 System.out.println(radiodetailsDTO1.toString());
		
		 
		 
}
	}